do try {return;} catch (Exception e){}while (true);