public class CompletionFindException1 {
	void foo(){
		try{
		} catch(Ex e) {
		}
	}
}